//! What the coding agents leave behind.
//!
//! Every other scanner here predates the thing this one exists for. A machine
//! that runs agents accumulates a second kind of debris beside the build
//! output: transcripts of every conversation, snapshots taken before every
//! edit, logs of every background run, and a package tree per tool. It lands in
//! dot-directories directly under `$HOME` — `~/.claude`, `~/.codex`, `~/.pi` —
//! which is the one place nothing else looks. Not the platform cache root, not
//! the application-support sweep, not the repository walk.
//!
//! The split that matters is inside those directories rather than between them.
//! A tool's `cache` and its finished job logs are regenerated by using it. Its
//! downloaded packages cost a re-download. Its session transcripts are the only
//! record that a piece of work happened at all, and no amount of re-running
//! brings one back — so they are offered the way `Personal` offers a download:
//! visible, one row per project, aged individually, and irreversible.
//!
//! A path this machine does not have is a rule that does not apply, which is
//! how one table covers every tool without asking which are installed. The
//! directories are rules like any other and take `[[agent]]` entries from the
//! configuration; the session *layouts* below stay in code, because a layout is
//! a scheme rather than a path and a configuration key naming one reap has not
//! been taught to read would produce rows it cannot label. A store named by a
//! configured rule is offered whole, which is the honest thing for a shape
//! nothing here understands.

use super::ScanOpts;
use crate::config::{AgentRule, RiskName, expand};
use crate::model::{Action, Candidate, Category, Risk, ScanEvent};
use crate::util::{human_age, now_secs, tilde};
use rayon::prelude::*;
use std::path::{Path, PathBuf};
use std::sync::mpsc::Sender;

/// `(path, tool, label, what it costs to lose, risk)`.
type Scratch = (
    &'static str,
    &'static str,
    &'static str,
    &'static str,
    RiskName,
);

/// The working directories, as opposed to the conversation history.
///
/// Graded by what it takes to get the bytes back: a cache the tool refills by
/// being used is safe, a package tree costs a download, and anything that is
/// the only record of an edit is not offered as either.
///
/// Every rule names the **narrowest directory that holds one kind of thing**,
/// which is rarely the one with the tool's name on it. `~/.claude/plugins`
/// looks like a cache and is not: `installed_plugins.json` and
/// `known_marketplaces.json` sit beside the downloaded content, and taking the
/// directory wholesale would lose the record of what you had installed while
/// claiming to have freed a cache. The rule names `plugins/cache`. The same
/// applies to `~/.pi/agent/npm`, whose `package.json` is the list of your
/// extensions and whose `node_modules` is the part that `npm install` puts
/// back.
const SCRATCH: &[Scratch] = &[
    // -- pi ----------------------------------------------------------------
    (
        "~/.pi/web-search-cache",
        "pi",
        "pi web-search cache",
        "pages fetched during a search · fetched again next time",
        RiskName::Safe,
    ),
    (
        "~/.pi/tasks",
        "pi",
        "pi background task output",
        "logs from background tasks that have already finished",
        RiskName::Safe,
    ),
    (
        "~/.pi/delegate",
        "pi",
        "pi delegate output",
        "results of delegated runs that have already been collected",
        RiskName::Safe,
    ),
    (
        "~/.pi/fusion",
        "pi",
        "pi fusion output",
        "results of fusion runs that have already been collected",
        RiskName::Safe,
    ),
    (
        // Not `npm/` itself: the manifest beside this is the record of which
        // extensions you chose, and it is what puts them back.
        "~/.pi/agent/npm/node_modules",
        "pi",
        "pi extension packages",
        "installed extensions and skills · re-installed from the manifest beside them",
        RiskName::Rebuildable,
    ),
    // -- Claude Code -------------------------------------------------------
    (
        "~/.claude/cache",
        "Claude Code",
        "Claude Code cache",
        "rebuilt as you use it",
        RiskName::Safe,
    ),
    (
        "~/.claude/paste-cache",
        "Claude Code",
        "Claude Code paste cache",
        "text pasted into sessions that have since ended",
        RiskName::Safe,
    ),
    (
        "~/.claude/shell-snapshots",
        "Claude Code",
        "Claude Code shell snapshots",
        "captured shell environments · re-captured on next session",
        RiskName::Safe,
    ),
    (
        "~/.claude/debug",
        "Claude Code",
        "Claude Code debug logs",
        "what the tool wrote down about itself",
        RiskName::Safe,
    ),
    (
        "~/.claude/jobs",
        "Claude Code",
        "Claude Code job output",
        "records of background jobs that have already finished",
        RiskName::Safe,
    ),
    (
        "~/.claude/downloads",
        "Claude Code",
        "Claude Code downloads",
        "what the tool staged for itself, releases and the like · fetched again on demand",
        RiskName::Rebuildable,
    ),
    (
        // Only the downloaded content. The directory above holds the record of
        // which plugins are installed and which marketplaces are trusted.
        "~/.claude/plugins/cache",
        "Claude Code",
        "Claude Code plugin cache",
        "downloaded plugin content · re-fetched from the marketplace that lists it",
        RiskName::Rebuildable,
    ),
    (
        "~/.claude/file-history",
        "Claude Code",
        "Claude Code file history",
        "the snapshots rewind restores from · the only record of an edit that was never committed",
        RiskName::Irreversible,
    ),
    // -- Codex -------------------------------------------------------------
    (
        "~/.codex/cache",
        "Codex",
        "Codex cache",
        "rebuilt as you use it",
        RiskName::Safe,
    ),
    (
        "~/.codex/log",
        "Codex",
        "Codex logs",
        "what the tool wrote down about itself",
        RiskName::Safe,
    ),
    (
        "~/.codex/shell_snapshots",
        "Codex",
        "Codex shell snapshots",
        "captured shell environments · re-captured on next session",
        RiskName::Safe,
    ),
    (
        // As with Claude Code: the cache, not the install record beside it.
        "~/.codex/plugins/cache",
        "Codex",
        "Codex plugin cache",
        "downloaded plugin content · re-fetched on demand",
        RiskName::Rebuildable,
    ),
    // -- Copilot CLI -------------------------------------------------------
    (
        "~/.copilot/logs",
        "Copilot CLI",
        "Copilot CLI logs",
        "what the tool wrote down about itself",
        RiskName::Safe,
    ),
    (
        "~/.copilot/pkg",
        "Copilot CLI",
        "Copilot CLI packages",
        "downloaded packages · re-downloaded on next run",
        RiskName::Rebuildable,
    ),
    (
        "~/.copilot/session-state",
        "Copilot CLI",
        "Copilot CLI session state",
        "what each session was doing when it ended",
        RiskName::Irreversible,
    ),
    // -- pi-lens -----------------------------------------------------------
    (
        "~/.pi-lens/logs",
        "pi-lens",
        "pi-lens logs",
        "what the tool wrote down about itself",
        RiskName::Safe,
    ),
    (
        "~/.pi-lens/projects",
        "pi-lens",
        "pi-lens project indexes",
        "the index it searches · rebuilt by re-reading the project",
        RiskName::Rebuildable,
    ),
    (
        "~/.pi-lens/bin",
        "pi-lens",
        "pi-lens binaries",
        "downloaded language servers and scanners · fetched again on demand",
        RiskName::Rebuildable,
    ),
    (
        // The manifest beside this is what reinstalls them, as with pi's own.
        "~/.pi-lens/tools/node_modules",
        "pi-lens",
        "pi-lens tool packages",
        "installed tooling · re-installed from the manifest beside it",
        RiskName::Rebuildable,
    ),
    // -- opencode ----------------------------------------------------------
    (
        "~/.local/share/opencode/log",
        "opencode",
        "opencode logs",
        "what the tool wrote down about itself",
        RiskName::Safe,
    ),
    (
        "~/.local/share/opencode/storage",
        "opencode",
        "opencode session store",
        "messages and sessions kept as files before the database took over",
        RiskName::Irreversible,
    ),
];

/// How a tool arranges the conversations it keeps.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Layout {
    /// One directory per project, named after the directory it belongs to with
    /// the separators flattened: `-Volumes-sourcecode-reap`.
    PerProject,
    /// `YYYY/MM/DD`, reported a month at a time.
    ByMonth,
}

/// `(path, tool, layout)`.
///
/// Reported one project or one month at a time rather than as a single lump,
/// because the question is never "do I want my history" — it is "do I still
/// need the history of *that*", and that question has an answer.
const SESSIONS: &[(&str, &str, Layout)] = &[
    ("~/.pi/agent/sessions", "pi", Layout::PerProject),
    ("~/.claude/projects", "Claude Code", Layout::PerProject),
    ("~/.gemini/tmp", "Gemini CLI", Layout::PerProject),
    ("~/.cursor/chats", "Cursor CLI", Layout::PerProject),
    ("~/.codex/sessions", "Codex", Layout::ByMonth),
];

/// The table above, as the rule set the scanner actually reads.
///
/// Seeds it; `[[agent]]` entries in the config add to it, and
/// `replace_builtin_agents` swaps it out entirely — the same arrangement the
/// artifact and cache rules have, so nothing here needs a recompile.
pub fn builtin_rules() -> Vec<AgentRule> {
    SCRATCH
        .iter()
        .map(|(path, tool, label, detail, risk)| AgentRule {
            path: (*path).to_string(),
            tool: (*tool).to_string(),
            label: (*label).to_string(),
            detail: (*detail).to_string(),
            risk: *risk,
        })
        .collect()
}

pub fn scan(opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let _ = tx.send(ScanEvent::Status("scanning coding agents".into()));

    // A path this machine does not have is a rule that does not apply, which is
    // how one table covers every tool without asking which are installed.
    let present: Vec<(&AgentRule, PathBuf)> = opts
        .rules
        .agents
        .iter()
        .map(|rule| (rule, expand(&rule.path)))
        .filter(|(_, path)| path.is_dir())
        .collect();

    present
        .par_iter()
        .for_each_with(tx.clone(), |tx, (rule, path)| {
            let size = opts.cache.size_of(path);
            if size < opts.min_size {
                return;
            }
            let Some(idle) = settled(path) else {
                return;
            };
            let detail = if rule.detail.is_empty() {
                tilde(path)
            } else {
                format!("{} · {}", tilde(path), rule.detail)
            };
            let cand = Candidate::new(
                Category::Agents,
                rule.tool.clone(),
                rule.label.clone(),
                detail,
                size,
                rule.risk.into(),
                Action::Remove(path.clone()),
            )
            .with_age(Some(idle));
            super::emit(tx, opts, cand);
        });

    let stores: Vec<(&str, Layout, PathBuf)> = SESSIONS
        .iter()
        .map(|(path, tool, layout)| (*tool, *layout, expand(path)))
        .filter(|(.., path)| path.is_dir())
        .collect();

    for (tool, layout, root) in stores {
        match layout {
            Layout::PerProject => per_project(tool, &root, opts, tx),
            Layout::ByMonth => by_month(tool, &root, opts, tx),
        }
    }
}

/// One row per project whose sessions the tool still holds.
///
/// The name on disk is the project's path with the separators flattened, so it
/// is resolved back to a real directory where it can be. That is what turns a
/// list of slugs nobody can read into a list of projects — and it surfaces the
/// rows worth looking at first, the ones whose project is no longer anywhere on
/// the machine.
pub fn per_project(tool: &str, root: &Path, opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let stores: Vec<PathBuf> = children(root);
    if stores.is_empty() {
        whole_store(tool, root, opts, tx);
        return;
    }
    stores.par_iter().for_each_with(tx.clone(), |tx, path| {
        let size = opts.cache.size_of(path);
        if size < opts.min_size {
            return;
        }
        let Some(idle) = settled(path) else {
            return;
        };
        let slug = file_name(path);
        // Shown as it is stored where it cannot be placed, minus the separators
        // that only ever stood in for a slash. Rewriting the rest into a path
        // would be the guess this deliberately refuses to make.
        let (name, whose) = match resolve_project(&slug) {
            Origin::Here(dir) => (
                file_name(&dir),
                format!("{} · every session for that project", tilde(&dir)),
            ),
            Origin::Missing => (
                slug.trim_matches('-').to_owned(),
                "no directory of that name is on this machine now — deleted, renamed, or on a \
                 volume that is not mounted"
                    .to_owned(),
            ),
            Origin::Opaque => (
                slug.trim_matches('-').to_owned(),
                "reap cannot tell which project this belongs to".to_owned(),
            ),
        };
        let detail = format!("{whose} · nothing written for {}", human_age(idle));
        let cand = Candidate::new(
            Category::Agents,
            tool,
            format!("{tool} · {name}"),
            detail,
            size,
            // Nothing regenerates a conversation. This is the same grading
            // Personal gives a file it cannot prove is downloadable, and for
            // the same reason.
            Risk::Danger,
            Action::Remove(path.clone()),
        )
        .with_age(Some(idle));
        super::emit(tx, opts, cand);
    });
}

/// One row per month, for a store filed by date rather than by project.
///
/// A row per day would be three hundred rows nobody reads. The whole tree as
/// one row would be a single all-or-nothing decision about years of history,
/// which is the decision people decline to make.
pub fn by_month(tool: &str, root: &Path, opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let mut months: Vec<(String, PathBuf)> = Vec::new();
    for year in children(root) {
        let name = file_name(&year);
        if !(name.len() == 4 && name.chars().all(|c| c.is_ascii_digit())) {
            continue;
        }
        for month in children(&year) {
            months.push((format!("{name}-{}", file_name(&month)), month));
        }
    }

    // A layout that stopped looking like dates is reported whole rather than
    // silently skipped: being wrong about the shape must not hide the bytes.
    if months.is_empty() {
        whole_store(tool, root, opts, tx);
        return;
    }

    months
        .par_iter()
        .for_each_with(tx.clone(), |tx, (when, path)| {
            let size = opts.cache.size_of(path);
            if size < opts.min_size {
                return;
            }
            let Some(idle) = settled(path) else {
                return;
            };
            let cand = Candidate::new(
                Category::Agents,
                tool,
                format!("{tool} sessions · {when}"),
                format!(
                    "{} · transcripts of every session that month · nothing written for {}",
                    tilde(path),
                    human_age(idle)
                ),
                size,
                Risk::Danger,
                Action::Remove(path.clone()),
            )
            .with_age(Some(idle));
            super::emit(tx, opts, cand);
        });
}

/// A session store reap could not break up, offered as one row.
///
/// The fallback for a layout that is not the shape this expects — a tool that
/// changed how it files things, or one whose scheme was read wrong here.
/// Reporting nothing would be the worse failure: not understanding a directory
/// is a fact about reap, and the disk is full either way. The row says as much,
/// so an all-or-nothing decision is not mistaken for a considered one.
fn whole_store(tool: &str, root: &Path, opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let size = opts.cache.size_of(root);
    if size < opts.min_size {
        return;
    }
    let Some(idle) = settled(root) else {
        return;
    };
    let cand = Candidate::new(
        Category::Agents,
        tool,
        format!("{tool} sessions"),
        format!(
            "{} · reap does not recognise how these are filed, so it offers them whole · \
             nothing written for {}",
            tilde(root),
            human_age(idle)
        ),
        size,
        Risk::Danger,
        Action::Remove(root.to_path_buf()),
    )
    .with_age(Some(idle));
    super::emit(tx, opts, cand);
}

/// How recently anything can have been written and the store still be called
/// finished.
///
/// This is a floor rather than a preference, and the one threshold here that
/// `--stale-days 0` cannot lower. A day is not a guess at how long a session
/// lasts; it is the smallest window in which "nothing at all has been written"
/// is a claim about the tool rather than about the moment reap happened to run.
const SETTLED_AFTER_SECS: u64 = 24 * 60 * 60;

/// How long a store has been finished, or `None` if it cannot be called that.
///
/// Everything else in this category rests on this answer, so it is taken from
/// the newest thing anywhere inside rather than from the directory's own
/// timestamp. The two differ exactly where it matters: a directory's mtime
/// moves when an entry is added and not when one is written to, and a
/// transcript is a file that gets appended to for as long as the session lasts.
/// A conversation running right now — or an old one resumed this morning —
/// leaves every directory above it stamped with the day it was created.
///
/// Reading that timestamp would offer a live session as three months idle. That
/// is the one mistake this scanner cannot make, since the row it would print
/// looks exactly like the rows that are safe to act on.
///
/// An unreadable tree yields `None`. Not being able to tell is never recorded
/// as having nothing to tell.
fn settled(path: &Path) -> Option<u64> {
    let newest = crate::util::newest_mtime(path)?;
    let idle = now_secs().saturating_sub(newest);
    (idle >= SETTLED_AFTER_SECS).then_some(idle / 86_400)
}

/// The subdirectories of `dir`, sorted, symlinks excluded.
fn children(dir: &Path) -> Vec<PathBuf> {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut out: Vec<PathBuf> = rd
        .flatten()
        // `is_dir` is false for symlinks, which keeps cycles out of the walk.
        .filter(|e| e.file_type().is_ok_and(|f| f.is_dir()))
        .map(|e| e.path())
        .collect();
    out.sort();
    out
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned()
}

/// How many directories `resolve_project` will look at before giving up.
///
/// The mapping is ambiguous, so resolving it is a search, and a name with
/// twenty dashes in a tree that half-matches it could otherwise cost thousands
/// of stat calls to answer a question worth one line of a detail column.
const RESOLUTION_BUDGET: usize = 256;

/// What can be said about the project a store was kept for.
///
/// Three answers rather than two, because "not found" covers two situations
/// that must not be worded alike. A name reap can read as a path and cannot
/// find is a real observation about the disk. A name it cannot read as a path
/// at all — a workspace id, a hash, a search it had to abandon — is an
/// observation about reap.
///
/// None of the three changes the grading. A store is irreversible whatever
/// became of the checkout: if anything, a project that is no longer there makes
/// its transcripts the last remaining record of that work rather than the
/// first thing safe to drop.
#[derive(Debug, PartialEq, Eq)]
enum Origin {
    /// The project is still on disk, at this path.
    Here(PathBuf),
    /// The name reads as a path, and nothing of that name is there now.
    ///
    /// Deliberately *not* called "deleted". An unmounted volume is
    /// indistinguishable from a removed directory from here, and this repository
    /// lives on one — so the row states what was observed and lets the reader,
    /// who knows whether they own an external disk, draw the conclusion.
    Missing,
    /// Nothing can be said about it.
    Opaque,
}

/// The directory a flattened project name came from, if it is still there.
///
/// `-Volumes-sourcecode-reap` is `/Volumes/sourcecode/reap` with every
/// separator replaced by a dash — and a dash is a legal character in a
/// directory name, so `-Volumes-sourcecode-my-project` has more than one
/// reading and string surgery cannot pick between them. The filesystem can:
/// at each level the longest run of dash-separated parts that names something
/// existing wins, and a reading that dead-ends further down is abandoned for
/// the next one.
///
/// Absence of an answer is never taken as proof of anything but its own
/// uncertainty. An unresolved store is still offered, still irreversible, and
/// says only that the project could not be found.
fn resolve_project(slug: &str) -> Origin {
    // Every path these tools flatten is absolute, so the name opens with the
    // separator. Anything else is a shape this does not know how to read — a
    // hash, a workspace id — and guessing at it would put a confident wrong
    // path in front of someone.
    //
    // A Windows path is one of those shapes. It starts at a drive rather than
    // at a separator, and how each tool spells that when flattening it is not
    // something reap has been shown rather than something it could assume. So
    // a store written on Windows is named as it is stored and says reap cannot
    // place it, which costs a label and claims nothing untrue — the row, its
    // size and its grading are all unaffected.
    //
    // How many dashes stand in for that separator is not agreed on: one tool
    // writes `-Volumes-sourcecode-reap`, another `--Volumes-sourcecode-reap--`.
    // Empty parts are dropped rather than counted, since neither spelling means
    // a directory whose name is nothing.
    if !slug.starts_with('-') {
        return Origin::Opaque;
    }
    let parts: Vec<&str> = slug.split('-').filter(|p| !p.is_empty()).collect();
    if parts.is_empty() {
        return Origin::Opaque;
    }
    let mut search = Search {
        budget: RESOLUTION_BUDGET,
        abandoned: false,
    };
    match descend(
        Path::new(std::path::MAIN_SEPARATOR_STR),
        &parts,
        &mut search,
    ) {
        Some(found) => Origin::Here(found),
        // An exhausted search is the only one that proves anything. One that
        // ran out of budget looked at some readings and not others, and "I did
        // not finish looking" must not be reported as "it is not there".
        None if search.abandoned => Origin::Opaque,
        None => Origin::Missing,
    }
}

/// State carried through one resolution, so a search that gives up says so.
struct Search {
    budget: usize,
    abandoned: bool,
}

fn descend(at: &Path, parts: &[&str], search: &mut Search) -> Option<PathBuf> {
    if parts.is_empty() {
        return Some(at.to_path_buf());
    }
    for take in (1..=parts.len()).rev() {
        if search.budget == 0 {
            search.abandoned = true;
            return None;
        }
        search.budget -= 1;
        let next = at.join(parts[..take].join("-"));
        if !next.is_dir() {
            continue;
        }
        if let Some(found) = descend(&next, &parts[take..], search) {
            return Some(found);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A tree under a scratch root, returned with the root.
    fn tree(name: &str, dirs: &[&str]) -> PathBuf {
        let root = std::env::temp_dir().join(format!("reap-agents-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        for dir in dirs {
            std::fs::create_dir_all(root.join(dir)).unwrap();
        }
        root
    }

    /// Resolve `slug` as if it named something under `root`.
    fn resolve_under(root: &Path, slug: &str) -> Option<PathBuf> {
        let mut search = Search {
            budget: RESOLUTION_BUDGET,
            abandoned: false,
        };
        let parts: Vec<&str> = slug.split('-').collect();
        descend(root, &parts, &mut search)
    }

    #[test]
    fn a_flattened_project_name_resolves_to_the_directory_it_came_from() {
        let root = tree("resolve", &["sourcecode/reap"]);
        assert_eq!(
            resolve_under(&root, "sourcecode-reap"),
            Some(root.join("sourcecode/reap"))
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_project_whose_own_name_holds_a_dash_still_resolves() {
        // The case string surgery gets wrong: `sourcecode-super-simple` has
        // three readings and only one of them exists.
        let root = tree("dashes", &["sourcecode/super-simple-factory"]);
        assert_eq!(
            resolve_under(&root, "sourcecode-super-simple-factory"),
            Some(root.join("sourcecode/super-simple-factory"))
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_reading_that_dead_ends_is_abandoned_for_the_next_one() {
        // `a-b` exists but holds nothing further, so the only whole reading is
        // the one through `a`. Stopping at the first level that matched would
        // report failure for a project that is right there.
        let root = tree("backtrack", &["a-b", "a/b/c"]);
        assert_eq!(resolve_under(&root, "a-b-c"), Some(root.join("a/b/c")));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_project_that_is_no_longer_there_resolves_to_nothing() {
        let root = tree("missing", &["sourcecode"]);
        assert_eq!(resolve_under(&root, "sourcecode-deleted-project"), None);
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_readable_name_that_is_not_there_is_reported_as_missing() {
        // The observation, not the conclusion. Somewhere under the root of the
        // filesystem there is no such directory — which is equally true of one
        // that was deleted and one on a volume that is not mounted, and this
        // cannot tell those apart, so it does not claim to.
        assert_eq!(
            resolve_project("-reap-spec-no-such-directory-anywhere"),
            Origin::Missing
        );
    }

    #[test]
    fn a_name_that_is_not_a_flattened_path_is_not_guessed_at() {
        // Workspace ids and hashes share the shape of a project name and mean
        // nothing like one. A confident wrong path is worse than no path, and
        // "nothing of that name exists" would be a claim about a path this
        // never had.
        assert_eq!(resolve_project("9f3c1ab2"), Origin::Opaque);
        assert_eq!(resolve_project("some-workspace-id"), Origin::Opaque);
        // A flattened Windows path, which starts at a drive rather than at a
        // separator. Specified rather than left to fall out of the leading-dash
        // check by accident: reap has not been shown how each tool spells a
        // drive, so it says so instead of inventing one.
        assert_eq!(resolve_project("C--Users-me-project"), Origin::Opaque);
        // Nothing but separators names no directory, and the root is not a
        // project. Answering `/` here would offer to delete a store while
        // claiming it belonged to the whole filesystem.
        assert_eq!(resolve_project("-"), Origin::Opaque);
        assert_eq!(resolve_project("--"), Origin::Opaque);
    }

    #[test]
    fn a_search_that_gives_up_says_so_rather_than_reporting_absence() {
        // A budget spent halfway through the readings of an ambiguous name has
        // looked at some and not others. Reporting that as "not there" would
        // turn running out of patience into a statement about the disk.
        let mut search = Search {
            budget: 0,
            abandoned: false,
        };
        assert_eq!(descend(Path::new("/"), &["anything"], &mut search), None);
        assert!(search.abandoned, "an exhausted budget must be recorded");
    }

    #[test]
    #[cfg(unix)]
    fn both_spellings_of_a_flattened_absolute_path_resolve_to_the_same_place() {
        // One tool writes a single leading dash, another wraps the name in
        // pairs of them. Reading only the first spelling would report every
        // project of the second as a checkout that is gone.
        let root = tree("spellings", &["project"]);
        let mut flat = String::new();
        for part in root.join("project").components().skip(1) {
            flat.push('-');
            flat.push_str(&part.as_os_str().to_string_lossy());
        }

        assert_eq!(
            resolve_project(&flat),
            Origin::Here(root.join("project")),
            "{flat}"
        );
        assert_eq!(
            resolve_project(&format!("-{flat}--")),
            Origin::Here(root.join("project"))
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn every_rule_names_an_anchored_path() {
        // A relative path would be resolved against whatever directory reap was
        // started in, and could match something nobody wrote it for.
        for (path, _, label, ..) in SCRATCH {
            assert!(
                path.starts_with("~/") || path.starts_with('%'),
                "{label} names {path}, which is not anchored anywhere"
            );
        }
        for (path, tool, _) in SESSIONS {
            assert!(
                path.starts_with("~/") || path.starts_with('%'),
                "{tool} names {path}, which is not anchored anywhere"
            );
        }
    }

    #[test]
    fn no_two_rules_name_the_same_path() {
        // Two rules on one path report the same bytes twice, and the figure at
        // the top of the screen is the number people act on.
        let mut paths: Vec<&str> = SCRATCH
            .iter()
            .map(|(p, ..)| *p)
            .chain(SESSIONS.iter().map(|(p, ..)| *p))
            .collect();
        paths.sort_unstable();
        let before = paths.len();
        paths.dedup();
        assert_eq!(paths.len(), before, "an agent path is listed twice");
    }

    /// Every path any rule names, session stores included.
    fn every_path() -> Vec<&'static str> {
        SCRATCH
            .iter()
            .map(|(p, ..)| *p)
            .chain(SESSIONS.iter().map(|(p, ..)| *p))
            .collect()
    }

    #[test]
    fn no_rule_nests_inside_another() {
        // The same bytes under two labels, with two different risks, and a
        // headline figure that counts them both. Worse here than elsewhere: the
        // two labels would disagree about whether the bytes are safe.
        for outer in every_path() {
            for inner in every_path() {
                assert!(
                    !inner.starts_with(&format!("{outer}/")),
                    "{inner} sits inside {outer}"
                );
            }
        }
    }

    #[test]
    fn no_rule_names_a_tools_top_level_directory() {
        // `~/.claude` holds settings, credentials and the record of what is
        // installed. Nothing that takes a whole tool's directory can be
        // describing one kind of thing, so this much is checkable from the
        // shape of the path alone.
        //
        // Only this much. Whether a directory *further* in mixes state with
        // content is a fact about that tool rather than about its path, and the
        // test below carries the cases where that was found to be true.
        for path in every_path() {
            let depth = path.trim_start_matches("~/").split('/').count();
            assert!(
                depth >= 2,
                "{path} names a tool's whole directory rather than one thing inside it"
            );
        }
    }

    #[test]
    fn the_rules_that_had_to_be_narrowed_stay_narrow() {
        // Each of these named the parent once, and each of those parents keeps
        // its bookkeeping beside the content it was named for:
        //
        //   ~/.pi/agent/npm      package.json — the list of your extensions,
        //                        and the thing that reinstalls them
        //   ~/.claude/plugins    installed_plugins.json, known_marketplaces.json
        //   ~/.codex/plugins     the same, for Codex
        //
        // Taking the parent frees the same bytes and quietly loses the record
        // of what you had, while the row calls itself a cache. Nothing about
        // the shape of those paths says so, so it is written down here: a
        // reader widening one of these has to delete a test that explains why
        // it is the way it is.
        for (parent, named) in [
            ("~/.pi/agent/npm", "~/.pi/agent/npm/node_modules"),
            ("~/.claude/plugins", "~/.claude/plugins/cache"),
            ("~/.codex/plugins", "~/.codex/plugins/cache"),
        ] {
            assert!(
                every_path().contains(&named),
                "{named} is no longer named by any rule"
            );
            assert!(
                !every_path().contains(&parent),
                "{parent} keeps its own bookkeeping beside the content — name {named}"
            );
        }
    }

    #[test]
    fn anything_holding_history_is_graded_irreversible() {
        // The safe tier is what `s` and the quick recipes take without asking,
        // so a transcript landing there is the one mistake this file must not
        // make. Matched on the path rather than on the grading, so a rule added
        // later is checked against what it names rather than against what
        // whoever added it believed.
        // "projects" is deliberately not among these. It describes a layout —
        // one directory per project — and says nothing about what is in them:
        // `~/.claude/projects` holds transcripts, `~/.pi-lens/projects` holds
        // search indexes that are rebuilt by re-reading the code. A guard that
        // cannot tell those apart would force the wrong grading onto whichever
        // one it met second, which is a test dictating a false fact rather than
        // catching one.
        for (path, _, label, _, risk) in SCRATCH {
            let holds_history = ["session", "history", "storage", "state"]
                .iter()
                .any(|word| path.contains(word));
            assert!(
                !holds_history || *risk == RiskName::Irreversible,
                "{label} ({path}) keeps history and is graded {risk:?}"
            );
        }
        // And every session store, whatever it is called, is graded in code
        // rather than in the table — which is what this asserts about the
        // table: none of them is in it.
        for (path, tool, _) in SESSIONS {
            assert!(
                !SCRATCH.iter().any(|(p, ..)| p == path),
                "{tool}'s store at {path} is graded twice"
            );
        }
    }
}
