use super::{ScanOpts, is_never_descend};
use crate::model::{Action, Candidate, Category, Risk, ScanEvent};
use crate::util::{age_days, human_age, tilde};
use rayon::prelude::*;
use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::sync::mpsc::Sender;

/// A directory that can be regenerated by its ecosystem's build tool.
struct Marker {
    /// Directory name to match.
    dir: &'static str,
    /// Sibling files that prove this really is what we think it is. An entry
    /// beginning with `*.` matches by extension. Empty means the name alone is
    /// unambiguous.
    evidence: &'static [&'static str],
    /// Tool that regenerates it, shown in the detail line.
    regen: &'static str,
    risk: Risk,
}

const MARKERS: &[Marker] = &[
    Marker { dir: "node_modules", evidence: &["package.json"], regen: "npm/pnpm install", risk: Risk::Caution },
    Marker { dir: "target", evidence: &["Cargo.toml"], regen: "cargo build", risk: Risk::Caution },
    Marker { dir: "bin", evidence: &["*.csproj", "*.fsproj", "*.vbproj", "*.sln"], regen: "dotnet build", risk: Risk::Caution },
    Marker { dir: "obj", evidence: &["*.csproj", "*.fsproj", "*.vbproj", "*.sln"], regen: "dotnet build", risk: Risk::Caution },
    Marker { dir: "dist", evidence: &["package.json"], regen: "npm run build", risk: Risk::Caution },
    Marker { dir: "out", evidence: &["package.json"], regen: "npm run build", risk: Risk::Caution },
    Marker { dir: "build", evidence: &["package.json", "CMakeLists.txt", "build.gradle", "build.gradle.kts"], regen: "the project build", risk: Risk::Caution },
    Marker { dir: ".next", evidence: &["package.json"], regen: "next build", risk: Risk::Caution },
    Marker { dir: ".nuxt", evidence: &["package.json"], regen: "nuxt build", risk: Risk::Caution },
    Marker { dir: ".turbo", evidence: &["package.json"], regen: "turbo", risk: Risk::Safe },
    Marker { dir: ".svelte-kit", evidence: &["package.json"], regen: "svelte-kit sync", risk: Risk::Caution },
    Marker { dir: ".angular", evidence: &["angular.json"], regen: "ng build", risk: Risk::Safe },
    Marker { dir: ".parcel-cache", evidence: &["package.json"], regen: "parcel", risk: Risk::Safe },
    Marker { dir: "coverage", evidence: &["package.json", "pyproject.toml"], regen: "the test suite", risk: Risk::Safe },
    Marker { dir: ".nyc_output", evidence: &["package.json"], regen: "the test suite", risk: Risk::Safe },
    Marker { dir: ".venv", evidence: &["pyproject.toml", "requirements.txt", "setup.py", "Pipfile"], regen: "pip install", risk: Risk::Caution },
    Marker { dir: "venv", evidence: &["pyproject.toml", "requirements.txt", "setup.py"], regen: "pip install", risk: Risk::Caution },
    Marker { dir: "__pycache__", evidence: &[], regen: "python", risk: Risk::Safe },
    Marker { dir: ".pytest_cache", evidence: &[], regen: "pytest", risk: Risk::Safe },
    Marker { dir: ".mypy_cache", evidence: &[], regen: "mypy", risk: Risk::Safe },
    Marker { dir: ".ruff_cache", evidence: &[], regen: "ruff", risk: Risk::Safe },
    Marker { dir: ".tox", evidence: &["tox.ini"], regen: "tox", risk: Risk::Caution },
    Marker { dir: ".gradle", evidence: &["build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"], regen: "gradle", risk: Risk::Caution },
    Marker { dir: "Pods", evidence: &["Podfile"], regen: "pod install", risk: Risk::Caution },
    Marker { dir: "vendor", evidence: &["composer.json"], regen: "composer install", risk: Risk::Caution },
    Marker { dir: "_build", evidence: &["mix.exs", "dune-project"], regen: "mix compile", risk: Risk::Caution },
    Marker { dir: "deps", evidence: &["mix.exs"], regen: "mix deps.get", risk: Risk::Caution },
    Marker { dir: ".terraform", evidence: &["*.tf"], regen: "terraform init", risk: Risk::Caution },
    Marker { dir: ".dart_tool", evidence: &["pubspec.yaml"], regen: "dart pub get", risk: Risk::Caution },
    Marker { dir: ".stack-work", evidence: &["stack.yaml"], regen: "stack build", risk: Risk::Caution },
    Marker { dir: "zig-cache", evidence: &["build.zig"], regen: "zig build", risk: Risk::Safe },
    Marker { dir: "zig-out", evidence: &["build.zig"], regen: "zig build", risk: Risk::Caution },
];

fn match_marker(name: &str, siblings: &HashSet<String>) -> Option<&'static Marker> {
    let m = MARKERS.iter().find(|m| m.dir == name)?;
    if m.evidence.is_empty() {
        return Some(m);
    }
    let ok = m.evidence.iter().any(|ev| match ev.strip_prefix("*.") {
        Some(ext) => siblings
            .iter()
            .any(|f| f.rsplit_once('.').is_some_and(|(_, e)| e == ext)),
        None => siblings.contains(*ev),
    });
    ok.then_some(m)
}

struct Hit {
    path: PathBuf,
    marker: &'static Marker,
}

pub fn scan(opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let mut hits = Vec::new();
    for root in &opts.roots {
        collect(root, 0, opts.max_depth, &mut hits);
    }
    // Catch strays sitting directly in $HOME — an `npm install` run in the
    // wrong directory leaves a node_modules no root would ever cover.
    if let Some(home) = super::home_dir() {
        let depth = opts.max_depth;
        collect(&home, depth, depth, &mut hits);
    }
    hits.sort_by(|a, b| a.path.cmp(&b.path));
    hits.dedup_by(|a, b| a.path == b.path);

    let _ = tx.send(ScanEvent::Status(format!(
        "sizing {} artifact directories",
        hits.len()
    )));

    // Sizing is the expensive part, so fan it out and stream results back as
    // each directory finishes.
    hits.par_iter().for_each_with(tx.clone(), |tx, hit| {
        let size = opts.cache.size_of(&hit.path);
        if size < opts.min_size {
            return;
        }
        let age = age_days(&hit.path);
        let project = hit
            .path
            .parent()
            .and_then(|p| p.file_name())
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default();

        let detail = match age {
            Some(d) => format!(
                "{} · untouched {} · restore with {}",
                tilde(hit.path.parent().unwrap_or(&hit.path)),
                human_age(d),
                hit.marker.regen
            ),
            None => format!("restore with {}", hit.marker.regen),
        };

        let cand = Candidate::new(
            Category::Artifacts,
            hit.marker.dir,
            format!("{project}/{}", hit.marker.dir),
            detail,
            size,
            hit.marker.risk,
            Action::Remove(hit.path.clone()),
        )
        .with_age(age);
        let _ = tx.send(ScanEvent::Found(Box::new(cand)));
    });
}

fn collect(dir: &Path, depth: usize, max_depth: usize, out: &mut Vec<Hit>) {
    if depth > max_depth {
        return;
    }
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };

    let mut subdirs: Vec<(String, PathBuf)> = Vec::new();
    let mut files: HashSet<String> = HashSet::new();
    for entry in rd.flatten() {
        let Ok(ft) = entry.file_type() else { continue };
        let name = entry.file_name().to_string_lossy().into_owned();
        if ft.is_dir() {
            subdirs.push((name, entry.path()));
        } else if ft.is_file() {
            files.insert(name);
        }
    }

    for (name, path) in subdirs {
        // Marker matching runs before the dot-directory filter, because plenty
        // of build output hides in `.next`, `.venv` and friends.
        if let Some(marker) = match_marker(&name, &files) {
            out.push(Hit { path, marker });
            continue;
        }
        if name.starts_with('.') || is_never_descend(&name) {
            continue;
        }
        collect(&path, depth + 1, max_depth, out);
    }
}
