use super::ScanOpts;
use crate::config::{CacheRule, RiskName, expand};
use crate::model::{Action, Candidate, Category, ScanEvent};
use crate::util::{age_days, path_size, tilde};
use rayon::prelude::*;
use std::path::PathBuf;
use std::sync::mpsc::Sender;

/// `(path, group, label, detail, risk, prune command)`.
///
/// Seeds the rule set; `[[cache]]` entries in the config add to it, and
/// `replace_builtin_caches` swaps it out entirely.
type BuiltinCache = (
    &'static str,
    &'static str,
    &'static str,
    &'static str,
    RiskName,
    &'static [&'static str],
);

const BUILTIN: &[BuiltinCache] = &[
    (
        "~/.npm/_cacache",
        "package managers",
        "npm cache",
        "re-downloaded on next install",
        RiskName::Safe,
        &[],
    ),
    (
        "~/Library/Caches/Yarn",
        "package managers",
        "yarn cache",
        "re-downloaded on next install",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.cache/yarn",
        "package managers",
        "yarn cache",
        "re-downloaded on next install",
        RiskName::Safe,
        &[],
    ),
    (
        "~/Library/pnpm/store",
        "package managers",
        "pnpm store",
        "hard-linked into existing installs — pruned, not deleted",
        RiskName::Rebuildable,
        &["pnpm", "store", "prune"],
    ),
    (
        "~/.local/share/pnpm/store",
        "package managers",
        "pnpm store",
        "hard-linked into existing installs — pruned, not deleted",
        RiskName::Rebuildable,
        &["pnpm", "store", "prune"],
    ),
    (
        "~/.bun/install/cache",
        "package managers",
        "bun cache",
        "re-downloaded on next install",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.nuget/packages",
        "package managers",
        "NuGet global packages",
        "every restored .NET package — re-downloaded on next restore",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/Library/Caches/NuGetHttpCache",
        "package managers",
        "NuGet HTTP cache",
        "re-downloaded on next restore",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.m2/repository",
        "package managers",
        "Maven repository",
        "re-downloaded on next build",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.gradle/caches",
        "package managers",
        "Gradle caches",
        "re-downloaded and re-built on next build",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cargo/registry/cache",
        "package managers",
        "cargo registry cache",
        "downloaded .crate archives",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.cargo/registry/src",
        "package managers",
        "cargo registry sources",
        "unpacked crate sources — re-extracted on next build",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.cargo/git/checkouts",
        "package managers",
        "cargo git checkouts",
        "git dependencies — re-cloned on next build",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/go/pkg/mod",
        "package managers",
        "Go module cache",
        "re-downloaded on next build",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cache/pip",
        "package managers",
        "pip cache",
        "re-downloaded on next install",
        RiskName::Safe,
        &[],
    ),
    (
        "~/Library/Caches/pip",
        "package managers",
        "pip cache",
        "re-downloaded on next install",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.cache/uv",
        "package managers",
        "uv cache",
        "re-downloaded on next install",
        RiskName::Safe,
        &[],
    ),
    (
        "~/Library/Caches/Homebrew",
        "package managers",
        "Homebrew downloads",
        "bottle archives already installed",
        RiskName::Safe,
        &["brew", "cleanup", "--prune=all"],
    ),
    (
        "~/Library/Caches/go-build",
        "compilers",
        "Go build cache",
        "rebuilt on next compile",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.cache/go-build",
        "compilers",
        "Go build cache",
        "rebuilt on next compile",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.dotnet/optimizationdata",
        "compilers",
        ".NET optimization data",
        "regenerated by the SDK",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.nvm/.cache",
        "compilers",
        "nvm download cache",
        "node tarballs already installed",
        RiskName::Safe,
        &[],
    ),
    (
        "~/Library/Developer/Xcode/DerivedData",
        "xcode",
        "Xcode DerivedData",
        "index and build products — rebuilt on next build",
        RiskName::Safe,
        &[],
    ),
    (
        "~/Library/Developer/Xcode/Archives",
        "xcode",
        "Xcode archives",
        "shipped app archives — needed to re-symbolicate old crash logs",
        RiskName::Irreversible,
        &[],
    ),
    (
        "~/Library/Developer/Xcode/iOS DeviceSupport",
        "xcode",
        "iOS device support",
        "symbols per device/OS — re-copied when you next attach a device",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/Library/Developer/CoreSimulator/Caches",
        "xcode",
        "Simulator caches",
        "regenerated by the simulator",
        RiskName::Safe,
        &[],
    ),
    (
        "~/Library/Caches/ms-playwright",
        "browsers",
        "Playwright browsers",
        "re-downloaded by `playwright install`",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cache/ms-playwright",
        "browsers",
        "Playwright browsers",
        "re-downloaded by `playwright install`",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cache/puppeteer",
        "browsers",
        "Puppeteer browsers",
        "re-downloaded on next install",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cache/pnpm",
        "package managers",
        "pnpm cache",
        "re-downloaded on next install",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.cache/deno",
        "package managers",
        "Deno cache",
        "re-downloaded on next run",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cache/pre-commit",
        "package managers",
        "pre-commit hooks",
        "rebuilt on next run",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cache/huggingface",
        "models",
        "Hugging Face cache",
        "downloaded model weights — large, and slow to re-fetch",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cache/torch",
        "models",
        "PyTorch cache",
        "downloaded model weights",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.cache/JetBrains",
        "editors",
        "JetBrains caches",
        "indexes, rebuilt on next open",
        RiskName::Safe,
        &[],
    ),
    (
        "~/.local/share/Trash",
        "system",
        "Trash",
        "already deleted — this empties it for good",
        RiskName::Rebuildable,
        &[],
    ),
    (
        "~/.Trash",
        "system",
        "Trash",
        "already deleted — this empties it for good",
        RiskName::Rebuildable,
        &[],
    ),
];

pub fn builtin_rules() -> Vec<CacheRule> {
    BUILTIN
        .iter()
        .map(|(path, group, label, detail, risk, prune)| CacheRule {
            path: (*path).to_string(),
            group: (*group).to_string(),
            label: (*label).to_string(),
            detail: (*detail).to_string(),
            risk: *risk,
            prune: prune.iter().map(|a| (*a).to_string()).collect(),
        })
        .collect()
}

/// Where unnamed application caches live, per platform.
fn unnamed_cache_root(home: &std::path::Path) -> PathBuf {
    if cfg!(target_os = "macos") {
        home.join("Library/Caches")
    } else {
        std::env::var_os("XDG_CACHE_HOME").map_or_else(|| home.join(".cache"), PathBuf::from)
    }
}

/// Entries under that root holding live state rather than a rebuildable cache.
const LIBRARY_CACHE_DENYLIST: &[&str] = &[
    "com.apple.containermanagerd",
    "com.apple.HomeKit",
    "CloudKit",
    "com.apple.iCloudHelper",
    "FamilyCircle",
];

pub fn scan(opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let _ = tx.send(ScanEvent::Status("scanning caches".into()));

    // Rules naming a path this machine does not have simply do not apply, which
    // is how one rule set covers macOS and Linux without branching.
    let present: Vec<(&CacheRule, PathBuf)> = opts
        .rules
        .caches
        .iter()
        .map(|rule| (rule, expand(&rule.path)))
        .filter(|(_, path)| path.exists())
        .collect();

    present
        .par_iter()
        .for_each_with(tx.clone(), |tx, (rule, path)| {
            let size = if path.is_dir() {
                opts.cache.size_of(path)
            } else {
                path_size(path)
            };
            if size < opts.min_size {
                return;
            }
            let action = match rule.prune.split_first() {
                Some((program, args)) => Action::Run {
                    program: program.clone(),
                    args: args.to_vec(),
                    cwd: None,
                },
                None => Action::Remove(path.clone()),
            };
            let detail = if rule.detail.is_empty() {
                tilde(path)
            } else {
                format!("{} · {}", tilde(path), rule.detail)
            };
            let cand = Candidate::new(
                Category::Caches,
                rule.group.clone(),
                rule.label.clone(),
                detail,
                size,
                rule.risk.into(),
                action,
            )
            .with_age(age_days(path));
            super::emit(tx, opts, cand);
        });

    if let Some(home) = super::home_dir() {
        library_caches(&home, opts, tx);
    }
}

/// Anything large under the platform's application-cache root that no rule
/// already names — `~/Library/Caches` on macOS, `~/.cache` elsewhere.
fn library_caches(home: &std::path::Path, opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let root = unnamed_cache_root(home);
    let Ok(rd) = std::fs::read_dir(&root) else {
        return;
    };
    // Anything a rule already covers is reported by that rule, with its own
    // wording and risk level.
    let known: Vec<String> = opts
        .rules
        .caches
        .iter()
        .filter_map(|r| {
            expand(&r.path)
                .strip_prefix(&root)
                .ok()
                .map(|p| p.to_string_lossy().into_owned())
        })
        .collect();

    let entries: Vec<PathBuf> = rd
        .flatten()
        .filter(|e| e.file_type().is_ok_and(|f| f.is_dir()))
        .map(|e| e.path())
        .filter(|p| {
            let name = p
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .into_owned();
            !known.contains(&name) && !LIBRARY_CACHE_DENYLIST.contains(&name.as_str())
        })
        .collect();

    // These are noisy, so only surface the ones actually worth a keystroke.
    let floor = opts.min_size.max(opts.rules.library_cache_floor);

    entries.par_iter().for_each_with(tx.clone(), |tx, path| {
        let size = opts.cache.size_of(path);
        if size < floor {
            return;
        }
        let name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let cand = Candidate::new(
            Category::Caches,
            "application caches",
            name,
            format!("{} · rebuilt by the owning app", tilde(path)),
            size,
            crate::model::Risk::Caution,
            Action::Remove(path.clone()),
        )
        .with_age(age_days(path));
        super::emit(tx, opts, cand);
    });
}
