use super::{ScanOpts, home_dir};
use crate::model::{Action, Candidate, Category, Risk, ScanEvent};
use crate::util::{age_days, path_size, tilde};
use rayon::prelude::*;
use std::path::PathBuf;
use std::sync::mpsc::Sender;

/// A well-known cache directory and how to clear it properly.
struct Spec {
    /// Path relative to `$HOME`.
    rel: &'static str,
    group: &'static str,
    label: &'static str,
    detail: &'static str,
    risk: Risk,
    /// Preferred command, when the tool has a cleaner that keeps its own
    /// bookkeeping consistent. `None` means a plain recursive delete is fine.
    prune: Option<(&'static str, &'static [&'static str])>,
}

const SPECS: &[Spec] = &[
    Spec { rel: ".npm/_cacache", group: "package managers", label: "npm cache", detail: "re-downloaded on next install", risk: Risk::Safe, prune: None },
    Spec { rel: "Library/Caches/Yarn", group: "package managers", label: "yarn cache", detail: "re-downloaded on next install", risk: Risk::Safe, prune: None },
    Spec { rel: ".cache/yarn", group: "package managers", label: "yarn cache", detail: "re-downloaded on next install", risk: Risk::Safe, prune: None },
    // The pnpm store is hard-linked into every node_modules on the machine, so
    // it must be pruned by pnpm rather than deleted out from under them.
    Spec { rel: "Library/pnpm/store", group: "package managers", label: "pnpm store", detail: "hard-linked into existing installs — pruned, not deleted", risk: Risk::Caution, prune: Some(("pnpm", &["store", "prune"])) },
    Spec { rel: ".local/share/pnpm/store", group: "package managers", label: "pnpm store", detail: "hard-linked into existing installs — pruned, not deleted", risk: Risk::Caution, prune: Some(("pnpm", &["store", "prune"])) },
    Spec { rel: ".bun/install/cache", group: "package managers", label: "bun cache", detail: "re-downloaded on next install", risk: Risk::Safe, prune: None },
    Spec { rel: ".nuget/packages", group: "package managers", label: "NuGet global packages", detail: "every restored .NET package — re-downloaded on next restore", risk: Risk::Caution, prune: None },
    Spec { rel: "Library/Caches/NuGetHttpCache", group: "package managers", label: "NuGet HTTP cache", detail: "re-downloaded on next restore", risk: Risk::Safe, prune: None },
    Spec { rel: ".m2/repository", group: "package managers", label: "Maven repository", detail: "re-downloaded on next build", risk: Risk::Caution, prune: None },
    Spec { rel: ".gradle/caches", group: "package managers", label: "Gradle caches", detail: "re-downloaded and re-built on next build", risk: Risk::Caution, prune: None },
    Spec { rel: ".cargo/registry/cache", group: "package managers", label: "cargo registry cache", detail: "downloaded .crate archives", risk: Risk::Safe, prune: None },
    Spec { rel: ".cargo/registry/src", group: "package managers", label: "cargo registry sources", detail: "unpacked crate sources — re-extracted on next build", risk: Risk::Safe, prune: None },
    Spec { rel: ".cargo/git/checkouts", group: "package managers", label: "cargo git checkouts", detail: "git dependencies — re-cloned on next build", risk: Risk::Caution, prune: None },
    Spec { rel: "go/pkg/mod", group: "package managers", label: "Go module cache", detail: "re-downloaded on next build", risk: Risk::Caution, prune: None },
    Spec { rel: ".cache/pip", group: "package managers", label: "pip cache", detail: "re-downloaded on next install", risk: Risk::Safe, prune: None },
    Spec { rel: "Library/Caches/pip", group: "package managers", label: "pip cache", detail: "re-downloaded on next install", risk: Risk::Safe, prune: None },
    Spec { rel: ".cache/uv", group: "package managers", label: "uv cache", detail: "re-downloaded on next install", risk: Risk::Safe, prune: None },
    Spec { rel: "Library/Caches/Homebrew", group: "package managers", label: "Homebrew downloads", detail: "bottle archives already installed", risk: Risk::Safe, prune: Some(("brew", &["cleanup", "--prune=all"])) },

    Spec { rel: "Library/Caches/go-build", group: "compilers", label: "Go build cache", detail: "rebuilt on next compile", risk: Risk::Safe, prune: None },
    Spec { rel: ".cache/go-build", group: "compilers", label: "Go build cache", detail: "rebuilt on next compile", risk: Risk::Safe, prune: None },
    Spec { rel: ".dotnet/optimizationdata", group: "compilers", label: ".NET optimization data", detail: "regenerated by the SDK", risk: Risk::Safe, prune: None },
    Spec { rel: ".nvm/.cache", group: "compilers", label: "nvm download cache", detail: "node tarballs already installed", risk: Risk::Safe, prune: None },

    Spec { rel: "Library/Developer/Xcode/DerivedData", group: "xcode", label: "Xcode DerivedData", detail: "index and build products — rebuilt on next build", risk: Risk::Safe, prune: None },
    Spec { rel: "Library/Developer/Xcode/Archives", group: "xcode", label: "Xcode archives", detail: "shipped app archives — needed to re-symbolicate old crash logs", risk: Risk::Danger, prune: None },
    Spec { rel: "Library/Developer/Xcode/iOS DeviceSupport", group: "xcode", label: "iOS device support", detail: "symbols per device/OS — re-copied when you next attach a device", risk: Risk::Caution, prune: None },
    Spec { rel: "Library/Developer/CoreSimulator/Caches", group: "xcode", label: "Simulator caches", detail: "regenerated by the simulator", risk: Risk::Safe, prune: None },

    Spec { rel: "Library/Caches/ms-playwright", group: "browsers", label: "Playwright browsers", detail: "re-downloaded by `playwright install`", risk: Risk::Caution, prune: None },
    Spec { rel: ".cache/ms-playwright", group: "browsers", label: "Playwright browsers", detail: "re-downloaded by `playwright install`", risk: Risk::Caution, prune: None },
    Spec { rel: ".cache/puppeteer", group: "browsers", label: "Puppeteer browsers", detail: "re-downloaded on next install", risk: Risk::Caution, prune: None },

    Spec { rel: ".Trash", group: "system", label: "Trash", detail: "already deleted — this empties it for good", risk: Risk::Caution, prune: None },
];

/// `~/Library/Caches` entries that hold live state rather than a rebuildable cache.
const LIBRARY_CACHE_DENYLIST: &[&str] = &[
    "com.apple.containermanagerd",
    "com.apple.HomeKit",
    "CloudKit",
    "com.apple.iCloudHelper",
    "FamilyCircle",
];

pub fn scan(opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let Some(home) = home_dir() else { return };
    let _ = tx.send(ScanEvent::Status("scanning caches".into()));

    let present: Vec<&Spec> = SPECS
        .iter()
        .filter(|s| home.join(s.rel).is_dir())
        .collect();

    present.par_iter().for_each_with(tx.clone(), |tx, spec| {
        let path = home.join(spec.rel);
        let size = if path.is_dir() { opts.cache.size_of(&path) } else { path_size(&path) };
        if size < opts.min_size {
            return;
        }
        let action = match spec.prune {
            Some((program, args)) => Action::Run {
                program: program.into(),
                args: args.iter().map(|a| a.to_string()).collect(),
                cwd: None,
            },
            None => Action::Remove(path.clone()),
        };
        let cand = Candidate::new(
            Category::Caches,
            spec.group,
            spec.label,
            format!("{} · {}", tilde(&path), spec.detail),
            size,
            spec.risk,
            action,
        )
        .with_age(age_days(&path));
        let _ = tx.send(ScanEvent::Found(Box::new(cand)));
    });

    library_caches(&home, opts, tx);
}

/// Anything large in `~/Library/Caches` that the table above does not already name.
fn library_caches(home: &std::path::Path, opts: &ScanOpts, tx: &Sender<ScanEvent>) {
    let root = home.join("Library/Caches");
    let Ok(rd) = std::fs::read_dir(&root) else {
        return;
    };
    let known: Vec<&str> = SPECS
        .iter()
        .filter_map(|s| s.rel.strip_prefix("Library/Caches/"))
        .collect();

    let entries: Vec<PathBuf> = rd
        .flatten()
        .filter(|e| e.file_type().map(|f| f.is_dir()).unwrap_or(false))
        .map(|e| e.path())
        .filter(|p| {
            let name = p.file_name().unwrap_or_default().to_string_lossy();
            !known.contains(&name.as_ref()) && !LIBRARY_CACHE_DENYLIST.contains(&name.as_ref())
        })
        .collect();

    // These are noisy, so only surface the ones actually worth a keystroke.
    let floor = opts.min_size.max(200 * 1024 * 1024);

    entries.par_iter().for_each_with(tx.clone(), |tx, path| {
        let size = path_size(path);
        if size < floor {
            return;
        }
        let name = path.file_name().unwrap_or_default().to_string_lossy().into_owned();
        let cand = Candidate::new(
            Category::Caches,
            "application caches",
            name,
            format!("{} · rebuilt by the owning app", tilde(path)),
            size,
            Risk::Caution,
            Action::Remove(path.clone()),
        )
        .with_age(age_days(path));
        let _ = tx.send(ScanEvent::Found(Box::new(cand)));
    });
}
